name: build wheels

on:
  push:
    tags:
      - "*"

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            arch: arm64
          - os: ubuntu-22.04
            arch: x86_64
          - os: ubuntu-22.04-arm
            arch: aarch64

    steps:
      - name: Step -- 1.
        uses: actions/checkout@v4

      - name: Step -- 2.
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Step -- 3.
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel

      - name: Step -- 4.
        env:
          CIBW_BUILD: "cp310-* cp311-* cp312-* cp313-* cp314-*"
          CIBW_BEFORE_ALL_LINUX: "command -v apk > /dev/null && apk add --no-cache curl-dev || true"
          CIBW_ARCHS_MACOS: ${{ matrix.arch }}
          CIBW_ARCHS_LINUX: ${{ matrix.arch }}
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - name: Step -- 5.
        uses: actions/upload-artifact@v5
        with:
          name: wheels-${{ matrix.name }}
          path: ./wheelhouse/*.whl

      - name: Step -- 6.
        run: |
          python -m pip install --upgrade twine
          python -m twine upload --skip-existing ./wheelhouse/*.whl
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_USERNAME: __token__
